tolerate pip 19.3 for --pyprof builds
The 'main' function was moved between pip 19.2.3 and 19.3, which
causes '--pyprof' build to fail with (at least) pip 19.3 and 19.3.1:

    Traceback (most recent call last):
      File "setup.py", line 37, in <module>
        pipmain(["install"] + required_packages)
    TypeError: 'module' object is not callable

A permanent solution for this might require rewriting the '--pyprof'
install section to use 'python -m pip', but this change just adjusts
the import to tolerate the 19.3 change.

See:

- https://github.com/pypa/pip/commit/09fd200c599de4fadf2ff814a1bef855bc6d77e8
- https://github.com/pypa/pip/issues/7498
- https://github.com/pypa/pip/pull/7499